### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by ghost** [stevegrunwell/wp-enforcer#35]
http://semver.org/#how-do-i-know-when-to-release-100

> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

**Comment by ghost** [comment]
Probably fix this first: https://github.com/stevegrunwell/wp-enforcer/issues/39

**Comment by stevegrunwell** [comment]
@jhabdas The pre-requisites for a 1.x release are outlined in [the milestone for that release](https://github.com/stevegrunwell/wp-enforcer/milestone/5), and are primarily centered around #20 — since that could affect the API in a more substantial way.

It's definitely a "feel it out" type thing, but since WP Enforcer should really only ever be used as a *dev* dependency the guidelines from that doc don't quite apply. Either way, thanks for linking to that FAQ, I don't think I've seen that particular guideline before! 👍

**Comment by ghost** [comment]
> Either way, thanks for linking to that FAQ, I don't think I've seen that particular guideline before!

I'm not sure if it was introduced in the 2.0 spec, but if you haven't reread SemVer since 1.0 it's worth absorbing as some things have changed. Either way, cutting a 1.0.0 early is a good practice and given the age of this project my advice is to consider updating your roadmap so those changes become a new major.

I don't have time to dig right now, but there're plenty of articles out there which will encourage projects to release a 1.0.0 early. The motto is _you've gotta have a one-dot-oh_. A lot of this came about in the community after Grunt got eternally stuck on a <del>major</del> <ins>minor release</ins>.

**EDIT:** I just checked and it looks like Grunt finally saw a 1.0 release. Took about two years (at which point most projects had already switched to Gulp anyway, so I guess it wasn't a very monumental announcement): https://github.com/gruntjs/grunt/releases

**Comment by jhabdas** [comment]
Also, I wish I'd have had a chance to respond before you decided to close this issue. But it's your project. That's just some feedback I want to give you to help you improve.
